/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NiBadge: typeof import('@/components/ui/badge')['Badge']
    NiButton: typeof import('@/components/ui/button')['Button']
    NiCard: typeof import('@/components/ui/card')['Card']
    NiCardContent: typeof import('@/components/ui/card')['CardContent']
    NiCardDescription: typeof import('@/components/ui/card')['CardDescription']
    NiCardHeader: typeof import('@/components/ui/card')['CardHeader']
    NiCardTitle: typeof import('@/components/ui/card')['CardTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('@/components/common/ThemeToggle')['ThemeToggle']
  }
}
